# Generated by Django 5.0.1 on 2024-08-24 20:21

import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Languages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Названия"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Код языка",
                    ),
                ),
                (
                    "icon",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True, null=True, upload_to="lng_icon"
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "lang",
            },
        ),
    ]
