# Generated by Django 5.0.1 on 2025-01-27 10:31

import core.models
import django.db.models.deletion
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.JSONField(validators=[core.models.json_field_validate]),
                ),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True, null=True, upload_to=""
                    ),
                ),
                ("order", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.JSONField(validators=[core.models.json_field_validate]),
                ),
                ("order", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.JSONField(validators=[core.models.json_field_validate]),
                ),
                ("description", models.JSONField(blank=True, null=True)),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True, null=True, upload_to=""
                    ),
                ),
                ("order", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="api.category",
                    ),
                ),
            ],
        ),
    ]
