# Generated by Django 5.0.1 on 2025-01-28 12:44

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_media_slider_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="image",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                default="some", upload_to=""
            ),
            preserve_default=False,
        ),
    ]
