# Generated by Django 5.0.1 on 2025-01-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_media_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "На рассмотрении"),
                            ("2", "Рассмотрено"),
                            ("3", "Отклонено"),
                        ],
                        default="1",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
