# Generated by Django 5.0.1 on 2025-01-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_application_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
