# Generated by Django 4.1 on 2025-03-26 16:50

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_audionews_book_videonews_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
