# Generated by Django 4.1 on 2025-03-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_audios_books_videos_delete_audionews_delete_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='some', editable=False, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='slug',
            field=models.SlugField(default='some', editable=False, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
