# Generated by Django 5.0.1 on 2024-08-24 20:15

import core.models
import django.db.models.deletion
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetaTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.JSONField(blank=True, null=True, verbose_name="Meta desk"),
                ),
                (
                    "meta_deck",
                    models.JSONField(blank=True, null=True, verbose_name="Meta desk"),
                ),
                (
                    "meta_keys",
                    models.JSONField(blank=True, null=True, verbose_name="Meta keys"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaticInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Заголовок сайта"
                    ),
                ),
                (
                    "subtitle",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Подзаголовок сайта"
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Описание сайта"
                    ),
                ),
                (
                    "about_us",
                    models.JSONField(blank=True, null=True, verbose_name="О нас"),
                ),
                (
                    "adres",
                    models.JSONField(blank=True, null=True, verbose_name="Адрес"),
                ),
                (
                    "logo_first",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        null=True,
                        upload_to="site_logo",
                        verbose_name="Лого сайта",
                    ),
                ),
                (
                    "logo_second",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        null=True,
                        upload_to="site_logo",
                        verbose_name="Второе лого",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Эмейл"
                    ),
                ),
                (
                    "telegram",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ссылка на телеграм",
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ссылка на инстаграм",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ссылка на фэйсбук",
                    ),
                ),
                (
                    "youtube",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Ютуб"
                    ),
                ),
                (
                    "nbm",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "map",
                    models.TextField(
                        blank=True, null=True, verbose_name="Iframe карты"
                    ),
                ),
                (
                    "work_time",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Время работы"
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "static_inf",
            },
        ),
        migrations.CreateModel(
            name="TranlsationGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                ("sub_text", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "transl_group",
            },
        ),
        migrations.CreateModel(
            name="Translations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                (
                    "value",
                    models.JSONField(
                        validators=[core.models.json_field_validate],
                        verbose_name="Значение",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="admins.tranlsationgroups",
                    ),
                ),
            ],
            options={
                "verbose_name": "transl",
                "unique_together": {("key", "group")},
            },
        ),
    ]
