# Generated by Django 5.0.1 on 2025-01-27 10:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translations",
            name="value",
            field=models.JSONField(validators=[core.models.json_field_validate]),
        ),
    ]
