# Generated by Django 4.1 on 2025-03-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_translations_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinformation',
            name='seo_description',
            field=models.JSONField(blank=True, null=True, verbose_name='SEO Описание'),
        ),
        migrations.AddField(
            model_name='staticinformation',
            name='seo_keywords',
            field=models.JSONField(blank=True, null=True, verbose_name='SEO Ключевые слова'),
        ),
        migrations.AddField(
            model_name='staticinformation',
            name='telegram_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Telegram канал'),
        ),
        migrations.AddField(
            model_name='staticinformation',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на YouTube канал'),
        ),
    ]
