# Generated by Django 4.1 on 2025-03-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_staticinformation_seo_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticinformation',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='staticinformation',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='staticinformation',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='staticinformation',
            name='youtube_link',
        ),
    ]
